DELIMITER ;
CREATE TABLE IF NOT EXISTS `blg_config` (
  `id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `tabellenzusatz` varchar(20) DEFAULT NULL,
  `ausgangslager` tinyint(4) DEFAULT 1,
  `eingangslager` tinyint(4) DEFAULT 1,
  `lager_faktor` int(11) DEFAULT -1,
  `kopftext` tinyint(4) DEFAULT 1,
  `fusstext` tinyint(4) DEFAULT 1,
  `adress_bezug` varchar(255) DEFAULT 'adressen',
  `preis_bezug` varchar(255) DEFAULT 'preis',
  `konten_bezug` varchar(50) DEFAULT '',
  `bw_faktor` int(11) DEFAULT 1,
  `preisorientierung` varchar(10) DEFAULT 'netto',
  `transitlager` int(11) DEFAULT 0,
  `pv_report_class` varchar(50) DEFAULT NULL,
  `gesperrt` tinyint(4) DEFAULT 0,
  `periodensperre` int(11) DEFAULT 1,
  `aktiv` int(11) DEFAULT 1,
  `login` varchar(255) DEFAULT NULL,
  `bestandspruefung` tinyint(4) DEFAULT 1,
  `auto_append_formel` tinyint(4) DEFAULT 0,
  `layout` int(11) DEFAULT 2,
  `bezug_id` varchar(36) DEFAULT 'id',
  `bezug_kst` varchar(36) DEFAULT NULL,
  `auto_lock` tinyint(4) DEFAULT 0,
  `belegnummer_von` bigint(20) DEFAULT 0,
  `belegnummer_bis` bigint(20) DEFAULT 0,
  `bezug_anzeigen` tinyint(4) DEFAULT 1,
  `brutto_anzeigen` tinyint(4) DEFAULT 1,
  `epreis_genauigkeit` int(11) DEFAULT 1,
  `filter_warengruppe` varchar(3) DEFAULT '-',
  `gegenkonto_bezug` varchar(10) DEFAULT NULL,
  `nur_kostenstelle_zusammenfassen` tinyint(4) DEFAULT 0,
  `use_history_pk` tinyint(4) DEFAULT 0,
  `mengen_genauigkeit` int(11) DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_blg_config_tz` (`tabellenzusatz`),
  KEY `idx_blg_config_preisorientierung` (`preisorientierung`),
  KEY `fk_blg_config_transitlager` (`transitlager`),
  CONSTRAINT `fk_blg_config_preisorientierung` FOREIGN KEY (`preisorientierung`) REFERENCES `preisorientierung` (`name`) ON UPDATE CASCADE,
  CONSTRAINT `fk_blg_config_transitlager` FOREIGN KEY (`transitlager`) REFERENCES `lager` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
