DELIMITER ;
INSERT INTO `ds` (`table_name`, `title`, `reorderfield`, `use_history`, `searchfield`, `displayfield`, `sortfield`, `searchany`, `hint`, `overview_tpl`, `sync_table`, `writetable`, `globalsearch`, `listselectionmodel`, `sync_view`, `syncable`, `cssstyle`, `alternativeformxtype`, `read_table`, `class_name`, `special_add_panel`, `existsreal`, `character_set_name`, `read_filter`, `listxtypeprefix`, `phpexporter`, `phpexporterfilename`, `combined`, `default_pagesize`, `allowForm`, `listviewbaseclass`, `showactionbtn`, `modelbaseclass`) VALUES ('kundenbetreuer','Kundenbetreuer','',0,'name','name','name',1,'','','','',0,'tualomultirowmodel','',0,'','','','ERP','',1,'','','listview','XlsxWriter','Kundenbetreuer-{DATE}',0,100,1,'Tualo.DataSets.ListView',1,'Tualo.DataSets.model.Basic') ON DUPLICATE KEY UPDATE title=VALUES(title), reorderfield=VALUES(reorderfield), use_history=VALUES(use_history), searchfield=VALUES(searchfield), displayfield=VALUES(displayfield), sortfield=VALUES(sortfield), searchany=VALUES(searchany), hint=VALUES(hint), overview_tpl=VALUES(overview_tpl), sync_table=VALUES(sync_table), writetable=VALUES(writetable), globalsearch=VALUES(globalsearch), listselectionmodel=VALUES(listselectionmodel), sync_view=VALUES(sync_view), syncable=VALUES(syncable), cssstyle=VALUES(cssstyle), alternativeformxtype=VALUES(alternativeformxtype), read_table=   VALUES(read_table), class_name=VALUES(class_name), special_add_panel=VALUES(special_add_panel), existsreal=VALUES(existsreal), character_set_name=VALUES(character_set_name), read_filter=VALUES(read_filter), listxtypeprefix=VALUES(listxtypeprefix), phpexporter=VALUES(phpexporter), phpexporterfilename=VALUES(phpexporterfilename), combined=VALUES(combined), default_pagesize=VALUES(default_pagesize), allowForm=VALUES(allowForm), listviewbaseclass=VALUES(listviewbaseclass), showactionbtn=VALUES(showactionbtn), modelbaseclass=VALUES(modelbaseclass);
INSERT  IGNORE INTO `ds_column` (`table_name`, `column_name`, `default_value`, `default_max_value`, `default_min_value`, `update_value`, `is_primary`, `syncable`, `referenced_table`, `referenced_column_name`, `is_nullable`, `is_referenced`, `writeable`, `note`, `data_type`, `column_key`, `column_type`, `character_maximum_length`, `numeric_precision`, `numeric_scale`, `character_set_name`, `privileges`, `existsreal`, `deferedload`, `hint`, `fieldtype`) VALUES ('kundenbetreuer','calendar',NULL,10000000,0,NULL,0,0,NULL,NULL,'YES','NO',1,'','tinyint','','tinyint(4)',NULL,3,0,NULL,'select,insert,update,references',1,0,NULL,''),
('kundenbetreuer','farbe',NULL,10000000,0,NULL,0,0,NULL,NULL,'YES','NO',1,'','varchar','','varchar(20)',20,NULL,NULL,'utf8mb4','select,insert,update,references',1,0,NULL,''),
('kundenbetreuer','id','{:uuid()}',10000000,0,'',1,0,'','','NO','NO',1,'','varchar','PRI','varchar(36)',36,NULL,NULL,'utf8mb4','select,insert,update,references',1,0,NULL,''),
('kundenbetreuer','login',NULL,10000000,0,NULL,0,0,NULL,NULL,'YES','NO',1,'','varchar','','varchar(100)',100,NULL,NULL,'utf8mb4','select,insert,update,references',1,0,NULL,''),
('kundenbetreuer','name',NULL,10000000,0,NULL,0,0,NULL,NULL,'NO','NO',1,'','varchar','UNI','varchar(150)',150,NULL,NULL,'utf8mb4','select,insert,update,references',1,0,NULL,'');
INSERT  IGNORE INTO `ds_column_list_label` (`table_name`, `column_name`, `language`, `label`, `xtype`, `editor`, `position`, `summaryrenderer`, `renderer`, `summarytype`, `hidden`, `active`, `filterstore`, `grouped`, `flex`, `direction`, `align`, `listfiltertype`, `hint`) VALUES ('kundenbetreuer','calendar','DE','calendar','checkcolumn','',999,'','','',0,1,'',0,1.00,'','','','NULL'),
('kundenbetreuer','farbe','DE','Farbe','rgbcolorcolumn','combobox_farben_rgb',2,'','','',0,1,'',0,1.00,'','','',NULL),
('kundenbetreuer','id','DE','ID','gridcolumn','',0,'','','',1,1,'',0,1.00,'ASC','left','',NULL),
('kundenbetreuer','login','DE','login','gridcolumn','combobox_view_session_users_login',999,'','','',0,1,'',0,1.00,'','','','NULL'),
('kundenbetreuer','name','DE','Name','gridcolumn','',1,'','','',0,1,'',0,1.00,'','','',NULL);
INSERT  IGNORE INTO `ds_column_form_label` (`table_name`, `column_name`, `language`, `label`, `xtype`, `field_path`, `position`, `hidden`, `active`, `allowempty`, `fieldgroup`, `flex`, `hint`) VALUES ('kundenbetreuer','farbe','DE','farbe','displayfield','Allgemein/Angaben',3,1,1,0,'',1.00,''),
('kundenbetreuer','id','DE','ID','displayfield','Allgemein/Angaben',0,0,1,1,'',1.00,''),
('kundenbetreuer','login','DE','Login','tualologins','Allgemein/Angaben',2,0,1,0,'',1.00,''),
('kundenbetreuer','name','DE','Name','textfield','Allgemein/Angaben',1,0,1,0,'',1.00,'');
INSERT  IGNORE INTO `ds_dropdownfields` (`table_name`, `name`, `idfield`, `displayfield`, `filterconfig`) VALUES ('kundenbetreuer','id','id','name',NULL);
INSERT  IGNORE INTO `ds_access` (`role`, `table_name`, `read`, `write`, `delete`, `append`, `existsreal`) VALUES ('administration','kundenbetreuer',0,1,1,1,0),
('_default_','kundenbetreuer',1,0,0,0,0);
INSERT  IGNORE INTO `ds_renderer` (`table_name`, `pug_template`, `label`, `orientation`, `useremote`) VALUES ('kundenbetreuer','vertriebsauswertung','Vertriebsauswertung','',1);
