DELIMITER ;
INSERT INTO `ds` (`table_name`, `title`, `reorderfield`, `use_history`, `searchfield`, `displayfield`, `sortfield`, `searchany`, `hint`, `overview_tpl`, `sync_table`, `writetable`, `globalsearch`, `listselectionmodel`, `sync_view`, `syncable`, `cssstyle`, `alternativeformxtype`, `read_table`, `class_name`, `special_add_panel`, `existsreal`, `character_set_name`, `read_filter`, `listxtypeprefix`, `phpexporter`, `phpexporterfilename`, `combined`, `default_pagesize`, `allowForm`, `listviewbaseclass`, `showactionbtn`, `modelbaseclass`) VALUES ('warengruppen','Warengruppen','wgsort',NULL,'warengruppe','warengruppe','id',NULL,NULL,NULL,NULL,NULL,NULL,'cellmodel',NULL,NULL,NULL,NULL,NULL,'ERP',NULL,1,NULL,NULL,NULL,'XlsxWriter','warengruppen {DATE} {TIME}',0,1000,1,'Tualo.DataSets.ListView',1,'Tualo.DataSets.model.Basic') ON DUPLICATE KEY UPDATE title=VALUES(title), reorderfield=VALUES(reorderfield), use_history=VALUES(use_history), searchfield=VALUES(searchfield), displayfield=VALUES(displayfield), sortfield=VALUES(sortfield), searchany=VALUES(searchany), hint=VALUES(hint), overview_tpl=VALUES(overview_tpl), sync_table=VALUES(sync_table), writetable=VALUES(writetable), globalsearch=VALUES(globalsearch), listselectionmodel=VALUES(listselectionmodel), sync_view=VALUES(sync_view), syncable=VALUES(syncable), cssstyle=VALUES(cssstyle), alternativeformxtype=VALUES(alternativeformxtype), read_table=   VALUES(read_table), class_name=VALUES(class_name), special_add_panel=VALUES(special_add_panel), existsreal=VALUES(existsreal), character_set_name=VALUES(character_set_name), read_filter=VALUES(read_filter), listxtypeprefix=VALUES(listxtypeprefix), phpexporter=VALUES(phpexporter), phpexporterfilename=VALUES(phpexporterfilename), combined=VALUES(combined), default_pagesize=VALUES(default_pagesize), allowForm=VALUES(allowForm), listviewbaseclass=VALUES(listviewbaseclass), showactionbtn=VALUES(showactionbtn), modelbaseclass=VALUES(modelbaseclass);
INSERT  IGNORE INTO `ds_column` (`table_name`, `column_name`, `default_value`, `default_max_value`, `default_min_value`, `update_value`, `is_primary`, `syncable`, `referenced_table`, `referenced_column_name`, `is_nullable`, `is_referenced`, `writeable`, `note`, `data_type`, `column_key`, `column_type`, `character_maximum_length`, `numeric_precision`, `numeric_scale`, `character_set_name`, `privileges`, `existsreal`, `deferedload`, `hint`, `fieldtype`) VALUES ('warengruppen','beleggruppierung',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'varchar','','varchar(20)',20,NULL,NULL,'utf8mb4','select,insert,update,references',1,NULL,NULL,''),
('warengruppen','farbe',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'varchar','','varchar(20)',20,NULL,NULL,'utf8mb4','select,insert,update,references',1,NULL,NULL,''),
('warengruppen','id','{#serial}',NULL,NULL,NULL,1,NULL,NULL,NULL,'NO',NULL,1,NULL,'int','PRI','int(11)',NULL,10,0,NULL,'select,insert,update,references',1,NULL,NULL,''),
('warengruppen','warengruppe',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'NO',NULL,1,NULL,'varchar','UNI','varchar(100)',100,NULL,NULL,'utf8mb4','select,insert,update,references',1,NULL,NULL,''),
('warengruppen','warenhauptgruppe',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'int','MUL','int(11)',NULL,10,0,NULL,'select,insert,update,references',1,NULL,NULL,''),
('warengruppen','wgsort',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'int','','int(11)',NULL,10,0,NULL,'select,insert,update,references',1,NULL,NULL,'');
INSERT  IGNORE INTO `ds_column_list_label` (`table_name`, `column_name`, `language`, `label`, `xtype`, `editor`, `position`, `summaryrenderer`, `renderer`, `summarytype`, `hidden`, `active`, `filterstore`, `grouped`, `flex`, `direction`, `align`, `listfiltertype`, `hint`) VALUES ('warengruppen','beleggruppierung','DE','Gruppierung','gridcolumn',NULL,0,'','','',1,1,'',0,1.00,'ASC','left','',NULL),
('warengruppen','farbe','DE','Farbe','column_farben_rgb',NULL,4,'','','',1,1,'',0,1.00,'ASC','left','',NULL),
('warengruppen','id','DE','ID','gridcolumn',NULL,1,'','','',0,1,'',0,1.00,'ASC','left','',NULL),
('warengruppen','warengruppe','DE','Name','gridcolumn',NULL,2,'','','',0,1,'',0,1.00,'ASC','left','',NULL),
('warengruppen','warenhauptgruppe','DE','Hauptgruppe','column_warenhauptgruppen_id',NULL,5,'','','',1,1,'',0,1.00,'ASC','left','',NULL),
('warengruppen','wgsort','DE','Sortierung','gridcolumn',NULL,3,'','','',1,1,'',0,1.00,'ASC','left','',NULL);
INSERT  IGNORE INTO `ds_column_form_label` (`table_name`, `column_name`, `language`, `label`, `xtype`, `field_path`, `position`, `hidden`, `active`, `allowempty`, `fieldgroup`, `flex`, `hint`) VALUES ('warengruppen','beleggruppierung','DE','Gruppierung','displayfield','Allgemein/Angaben',0,0,1,NULL,NULL,NULL,'\'\''),
('warengruppen','farbe','DE','Farbe','combobox_farben_rgb','Allgemein/Angaben',4,0,1,NULL,NULL,NULL,'\'\''),
('warengruppen','id','DE','ID','displayfield','Allgemein/Angaben',1,0,1,NULL,NULL,NULL,'\'\''),
('warengruppen','warengruppe','DE','Name','textfield','Allgemein/Angaben',2,0,1,NULL,NULL,NULL,'\'\''),
('warengruppen','warenhauptgruppe','DE','Hauptgruppe','combobox_warenhauptgruppen_id','Allgemein/Angaben',5,0,1,NULL,NULL,NULL,'\'\''),
('warengruppen','wgsort','DE','Sortierung','displayfield','Allgemein/Angaben',3,0,1,NULL,NULL,NULL,'\'\'');
INSERT  IGNORE INTO `ds_dropdownfields` (`table_name`, `name`, `idfield`, `displayfield`, `filterconfig`) VALUES ('warengruppen','warengruppe','warengruppe','warengruppe','');
INSERT  IGNORE INTO `ds_reference_tables` (`table_name`, `reference_table_name`, `columnsdef`, `constraint_name`, `active`, `searchable`, `autosync`, `position`, `path`, `existsreal`, `tabtitle`) VALUES ('warengruppen','warenhauptgruppen','{\"warenhauptgruppe\":\"id\"}','fk_waregruppen_warenhauptgruppe',0,0,0,999,'',1,'');
INSERT  IGNORE INTO `ds_access` (`role`, `table_name`, `read`, `write`, `delete`, `append`, `existsreal`) VALUES ('administration','warengruppen',1,1,1,1,NULL),
('_default_','warengruppen',1,NULL,NULL,NULL,NULL);
